import { Button, VerticalBox, LineEdit, HorizontalBox} from "std-widgets.slint";

component CalculateButton inherits Button {
    text: "Calculate";
    // on-clicked: request-increase-value();
    primary: true;
    
}

export component AppWindow inherits Window {
    in property <string> result: "";
    in-out property <bool> opencurtain;
    callback divide_income(string);
    background: white;
    title: "Income Tax Calculator";
    VerticalBox {
        padding: 50px;
        spacing: 25px;
        HorizontalLayout {
            Text {
                text: "Enter Total Income";
                horizontal-alignment: center;
                font-size: 24px;
                font-weight: 900;
            }
        }

        HorizontalLayout {
            income := LineEdit {
                horizontal-alignment: center;
                font-size: 16px;
                placeholder-text: "Enter your number";
            }
        }
        HorizontalLayout{
            CalculateButton {
                clicked => {
                    root.opencurtain = !root.opencurtain;
                    divide-income(income.text)
                } 
            }
        }
        HorizontalLayout {
            VerticalBox {
                height: 100px;
                width: 150px;
                Rectangle {
                    height: 100px;
                    background: #f2f2f2;
                    Text {
                        text: root.result;
                        horizontal-alignment: center;
                        font-size: 16px;
                        font-weight: 500;
                    }
                }
                Rectangle {
                    background: white;
                    x: 0;
                    width: opencurtain ? 0 : parent.width/2;
                    height: parent.height;
                    animate width {
                         duration: 250ms;
                         easing: ease-in;
                    }
                }
                Rectangle {
                    background: white;
                    width: opencurtain ? parent.width : parent.width/2;
                    height: parent.height;
                    animate width {
                         duration: 250ms;
                         easing: ease-in;
                         
                    }
                    animate x {
                         duration: 250ms;
                         easing: ease-in;
                         
                    }
                }
            }
        }
    }
}
